language: c
os: linux
sudo: required
dist: xenial
branches:
  only:
    - master
    - coverity_scan
jobs:
  include:
    - stage: "Package"
      name: "Debian packages"
      script:
        - gbp buildpackage
env:
  global:
   - secure: "Noxed1PEztsf6kRoFy17lmrsDW75SM6NK3lkHQ8yeyYvDtF3vzHXJ4TAgpcDA1RLuzOLvSjnkuucjWb8YLoisW3qs31h26qeZzN+PbeaMYFmtmkZJOiPorbtHYA47pB2xfdujoi1kSne/fHFXY0Jybj2DcUbYUS+9plnZ+4pV2w="
addons:
  apt:
    packages:
    - cdbs
    - debhelper
    - dh-autoreconf
    - fakeroot
    - git-buildpackage
    - libev-dev
    - libpcap-dev
    - libsodium-dev
    - pkg-config
    - ruby-ronn
  coverity_scan:
    project:
      name: "zehome/MLVPN"
      description: "Build submitted via Travis CI"
    notification_email: ed@zehome.com
    build_command_prepend: "./autogen.sh && ./configure && make clean"
    build_command: "make"
    branch_pattern: coverity_scan
