language: c
os: linux
compiler:
  - gcc
#  - clang
branches:
  only:
    - ev
    - debian-unstable
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libev-dev automake autoconf
  - git clone git://github.com/jedisct1/libsodium.git && cd libsodium
  - ./autogen.sh && ./configure && make check
  - sudo make install && sudo ldconfig
  - cd ..
script:
  - ./autogen.sh && ./configure && make V=1 && make install
env:
  global:
   - secure: "Noxed1PEztsf6kRoFy17lmrsDW75SM6NK3lkHQ8yeyYvDtF3vzHXJ4TAgpcDA1RLuzOLvSjnkuucjWb8YLoisW3qs31h26qeZzN+PbeaMYFmtmkZJOiPorbtHYA47pB2xfdujoi1kSne/fHFXY0Jybj2DcUbYUS+9plnZ+4pV2w="
addons:
  coverity_scan:
    project:
      name: "zehome/MLVPN"
      description: "Build submitted via Travis CI"
    notification_email: ed@zehome.com
    build_command_prepend: "./autogen.sh && ./configure && make clean"
    build_command: "make"
    branch_pattern: ev
