language: c
os: linux
compiler:
  - gcc
  - clang
branches:
  only:
    - ev
    - debian-unstable
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libev-dev automake autoconf
  - git clone git://github.com/jedisct1/libsodium.git && cd libsodium
  - ./autogen.sh && ./configure && make check
  - sudo make install && sudo ldconfig
  - cd ..
run:
  - ./autogen.sh && ./configure && make && make install
